### ISSUE TITLE
Too nested if else

### ISSUE THREAD

**Issue by ShaharAriel** [ShmuelSafrin/ManagementDebtorsList#4]
Try avoiding to make too nested ` if else`
https://github.com/ShmuelSafrin/ManagementDebtorsList/blob/3b57ad317eb3e9fb6f8ecf9675f9adf3b06c8861/ManagementDebtorsList/buildDeleteFuncs.c#L627

**Comment by meni181818** [comment]
maybe it's a good idea to separate long/nested code -> into several functions.
every function should do one specific thing.
if you have afunction that is more then 5 lines of code - that not a good sign. unless you have realy good reason.

**Comment by ShmuelSafrin** [comment]
Thank you very much may I share a screen with you by zoom because I
understood your comments but I don't know hou to applie them for example to
make while for all strtok: how should I now which field is it?  In order to
make the appropriate validations check

בתאריך יום ב׳, 9 במאי 2022, 12:09, מאת meni181818 ***@***.***

**Comment by meni181818** [comment]
i'd really love to help, but i'm not sure about today..
about strtok: i think you dont have to use while for that. you can move from token to token and every time check `if (token != NULL)` or `if (token == NULL)`

**Comment by ShmuelSafrin** [comment]
lll
